### ISSUE TITLE
comilation error `(error "Eager macro-expansion failure: (void-function @--walk)")`

### ISSUE THREAD

**Issue by jian-lin** [skeeto/at-el#9]
steps to reproduce:
1. `emacs -Q --init-directory=$(mktemp -d)`
2. eval this:
```elisp
(progn
  (setq byte-compile-debug t)
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (package-refresh-contents)
  (package-install '@))
```
3. you see the error `(error "Eager macro-expansion failure: (void-function @--walk)")`

ref: https://github.com/NixOS/nixpkgs/issues/335442

**Comment by skeeto** [comment]
I thought maybe this was something new, but I could reproduce the issue locally on old Emacs versions by compiling/loading "out of order." (I've never used @ from MELPA, and I haven't loaded a package from MELPA in some years.) I think 0489e15 fixes it.

**Comment by jian-lin** [comment]
That patch looks good to me and I have verified that the error cannot be reproduced with that patch applied.

Thanks.
